/**
 * Source Map Optimizer
 *
 * This module optimizes source maps generated by the Botpress CLI (`bp dev` and `bp build`)
 * by removing sources that fall outside the agent's src directory.
 *
 * ## Problem
 * The bundled bot includes source maps that reference ALL sources, including:
 * - Agent's own code (~10 files)
 * - All node_modules dependencies (~10,000+ files)
 * - Botpress SDK internals
 *
 * This results in source maps that are 30+ MB, where 99% of the content is from
 * dependencies the user doesn't care about when debugging their agent.
 *
 * ## Solution
 * 1. Parse the source map and identify which sources are inside the agent's src directory
 * 2. Decode the VLQ mappings in a single pass, retaining only the segments that
 *    reference a kept source (plus generated-column-only markers)
 * 3. Re-encode the (tiny) retained set with compacted source/name indices
 * 4. Save both an optimized .map file AND inline it into the .cjs bundle
 *
 * ## What is VLQ?
 * Variable Length Quantity (VLQ) is a compact encoding format used in source maps.
 * Source maps use VLQ to encode the "mappings" string, which contains information about
 * how each position in the generated code maps back to the original source.
 *
 * Each segment in the mappings can contain up to 5 fields (all VLQ-encoded):
 * 1. Column position in the generated code
 * 2. Source file index (into the sources array)
 * 3. Line number in the original source
 * 4. Column position in the original source
 * 5. Name index (into the names array) - optional
 *
 * The mappings string uses:
 * - `;` to separate lines
 * - `,` to separate segments within a line
 * - Base64 characters to encode VLQ values
 *
 * ## Performance
 * The decode is unavoidable — source/name indices are cumulative deltas, so every
 * segment must be decoded to keep the running state correct even for the ~99% that
 * get dropped. But we avoid the two dominant costs of a naive decoder: we never
 * allocate a tuple per VLQ field (a shared cursor is advanced in place), and we
 * only materialize an object for segments we actually keep. For an agent bundle
 * that turns millions of allocations into thousands.
 */

import { readFile, writeFile } from 'fs/promises'
import { resolve, isAbsolute, relative, dirname } from 'path'
import { AdkError } from '@holocronlab/botruntime-analytics'

export interface SourceMapOptimizeOptions {
  /**
   * Path to the source map file (.cjs.map)
   */
  sourceMapPath: string

  /**
   * Path to the agent's src directory.
   * Sources outside this directory will be removed.
   */
  agentSrcPath: string
}

interface SourceMap {
  version: number
  sources: string[]
  sourcesContent?: (string | null)[]
  mappings: string
  names?: string[]
  file?: string
  sourceRoot?: string
}

/** A retained mapping segment, with absolute (un-delta'd) values and original indices. */
interface KeptSegment {
  column: number
  sourceIndex?: number
  sourceLine?: number
  sourceColumn?: number
  nameIndex?: number
}

/**
 * Encodes a number as VLQ
 */
function encodeVLQ(value: number): string {
  const base64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

  let encoded = ''
  let num = value < 0 ? (-value << 1) | 1 : value << 1

  do {
    let digit = num & 31
    num >>>= 5
    if (num > 0) {
      digit |= 32
    }
    encoded += base64[digit]
  } while (num > 0)

  return encoded
}

/**
 * Decodes the VLQ mappings string in a single pass, retaining only the segments
 * that reference a kept source (and generated-column-only markers, which carry no
 * source). Every segment is decoded so the running delta state stays correct, but
 * only retained segments are materialized.
 *
 * Returns the retained segments grouped by generated line, the total generated
 * line count (so the re-encode can preserve line positions), and the set of name
 * indices actually referenced by retained segments.
 */
function collectKeptSegments(
  mappings: string,
  indicesToKeep: Set<number>
): { keptByLine: Map<number, KeptSegment[]>; totalLines: number; usedNameIndices: Set<number> } {
  const keptByLine = new Map<number, KeptSegment[]>()
  const usedNameIndices = new Set<number>()

  const len = mappings.length
  let pos = 0

  // Running decode state. Generated column resets per line; the rest are
  // continuous across the whole mappings string.
  let line = 0
  let genColumn = 0
  let sourceIndex = 0
  let sourceLine = 0
  let sourceColumn = 0
  let nameIndex = 0

  // Non-allocating VLQ read: consumes from `mappings` starting at `pos` and
  // advances `pos` in place (no per-field tuple allocation).
  const readVLQ = (): number => {
    let result = 0
    let shift = 0
    let continuation = true

    while (continuation) {
      if (pos >= len) {
        throw new AdkError({
          code: 'SOURCEMAP_DECODE_ERROR',
          message: 'Unexpected end of VLQ data',
        })
      }

      const char = mappings.charCodeAt(pos++)
      let digit: number
      // Base64 decode
      if (char >= 65 && char <= 90)
        digit = char - 65 // A-Z
      else if (char >= 97 && char <= 122)
        digit = char - 97 + 26 // a-z
      else if (char >= 48 && char <= 57)
        digit = char - 48 + 52 // 0-9
      else if (char === 43)
        digit = 62 // +
      else if (char === 47)
        digit = 63 // /
      else throw new AdkError({ code: 'SOURCEMAP_DECODE_ERROR', message: 'Invalid VLQ character' })

      continuation = (digit & 32) !== 0
      digit &= 31
      result += digit << shift
      shift += 5
    }

    const negate = (result & 1) === 1
    result >>= 1
    return negate ? -result : result
  }

  // A further field exists in the current segment iff the next char isn't a
  // segment (`,`) or line (`;`) separator.
  const hasMoreFields = (): boolean => {
    if (pos >= len) return false
    const c = mappings.charCodeAt(pos)
    return c !== 44 /* , */ && c !== 59 /* ; */
  }

  while (pos < len) {
    const char = mappings.charCodeAt(pos)
    if (char === 59 /* ; */) {
      line++
      genColumn = 0
      pos++
      continue
    }
    if (char === 44 /* , */) {
      pos++
      continue
    }

    // Field 1: generated column (always present)
    genColumn += readVLQ()

    let segSourceIndex: number | undefined
    let segSourceLine: number | undefined
    let segSourceColumn: number | undefined
    let segNameIndex: number | undefined

    if (hasMoreFields()) {
      sourceIndex += readVLQ()
      segSourceIndex = sourceIndex

      if (hasMoreFields()) {
        sourceLine += readVLQ()
        segSourceLine = sourceLine

        if (hasMoreFields()) {
          sourceColumn += readVLQ()
          segSourceColumn = sourceColumn

          if (hasMoreFields()) {
            nameIndex += readVLQ()
            segNameIndex = nameIndex
          }
        }
      }
    }

    // Keep generated-column-only markers and segments mapping to a kept source.
    if (segSourceIndex === undefined || indicesToKeep.has(segSourceIndex)) {
      let segs = keptByLine.get(line)
      if (!segs) {
        segs = []
        keptByLine.set(line, segs)
      }
      segs.push({
        column: genColumn,
        sourceIndex: segSourceIndex,
        sourceLine: segSourceLine,
        sourceColumn: segSourceColumn,
        nameIndex: segNameIndex,
      })
      // A name only follows the source fields, so a defined name here implies a
      // kept source — matching the original "used name" rule.
      if (segNameIndex !== undefined) {
        usedNameIndices.add(segNameIndex)
      }
    }
  }

  return { keptByLine, totalLines: line + 1, usedNameIndices }
}

/**
 * Re-encodes the retained segments into a mappings string, remapping source and
 * name indices to their compacted positions. Output is byte-identical to decoding
 * then dropping the removed segments: generated line positions are preserved
 * (empty lines emit nothing between `;`), generated column deltas reset per line,
 * and source/name deltas are continuous across lines.
 */
function encodeKeptSegments(
  keptByLine: Map<number, KeptSegment[]>,
  totalLines: number,
  sourceIndexMap: Map<number, number>,
  nameIndexMap: Map<number, number>
): string {
  const lines: string[] = []
  let prevSourceIndex = 0
  let prevSourceLine = 0
  let prevSourceColumn = 0
  let prevNameIndex = 0

  for (let line = 0; line < totalLines; line++) {
    const segs = keptByLine.get(line)
    if (!segs) {
      lines.push('')
      continue
    }

    let prevColumn = 0
    const parts: string[] = []

    for (const seg of segs) {
      let encoded = encodeVLQ(seg.column - prevColumn)
      prevColumn = seg.column

      if (seg.sourceIndex !== undefined) {
        const newSourceIndex = sourceIndexMap.get(seg.sourceIndex)!
        encoded += encodeVLQ(newSourceIndex - prevSourceIndex)
        prevSourceIndex = newSourceIndex

        if (seg.sourceLine !== undefined) {
          encoded += encodeVLQ(seg.sourceLine - prevSourceLine)
          prevSourceLine = seg.sourceLine

          if (seg.sourceColumn !== undefined) {
            encoded += encodeVLQ(seg.sourceColumn - prevSourceColumn)
            prevSourceColumn = seg.sourceColumn

            if (seg.nameIndex !== undefined) {
              const newNameIndex = nameIndexMap.get(seg.nameIndex)
              if (newNameIndex !== undefined) {
                encoded += encodeVLQ(newNameIndex - prevNameIndex)
                prevNameIndex = newNameIndex
              }
            }
          }
        }
      }

      parts.push(encoded)
    }

    lines.push(parts.join(','))
  }

  return lines.join(';')
}

/**
 * Optimizes a source map by removing sources that fall outside
 * the agent's src directory and rebuilding the mappings.
 *
 * This dramatically reduces the size of the source map (typically 90%+ reduction)
 * without losing valuable debugging information for the agent's own code.
 *
 * The optimized source map is both:
 * 1. Written to the .map file (for external reference)
 * 2. Inlined as base64 into the .cjs bundle (for runtime debugging)
 *
 * We inline the source map because after optimization it's tiny (usually <1MB),
 * which makes it much easier for tools like VSCode and Chrome DevTools to load
 * and use for debugging. Inline source maps eliminate the need for additional
 * HTTP requests or file system lookups, providing instant source mapping.
 *
 * @param options - Configuration options
 * @returns Promise that resolves when the source map has been optimized
 */
export async function optimizeSourceMap(options: SourceMapOptimizeOptions): Promise<void> {
  const { sourceMapPath, agentSrcPath } = options

  // Read and parse the source map
  const sourceMapContent = await readFile(sourceMapPath, 'utf-8')
  const sourceMap: SourceMap = JSON.parse(sourceMapContent)

  // Resolve absolute paths for comparison
  const resolvedAgentSrc = resolve(agentSrcPath)
  const sourceMapDir = resolve(sourceMapPath, '..')

  // Track indices to keep (agent sources only)
  const indicesToKeep = new Set<number>()

  // Find all sources that should be kept (inside agent src directory)
  for (let i = 0; i < sourceMap.sources.length; i++) {
    const source = sourceMap.sources[i]
    if (!source) {
      continue
    }

    // Resolve the source path from the source map's directory
    const resolvedSource = isAbsolute(source) ? resolve(source) : resolve(sourceMapDir, source)

    // Check if this source is inside the agent src directory
    const rel = relative(resolvedAgentSrc, resolvedSource)
    const isInside = !rel.startsWith('..') && !isAbsolute(rel)

    if (isInside) {
      indicesToKeep.add(i)
    }
  }

  // Decode the mappings once, keeping only the retained segments + used names.
  const { keptByLine, totalLines, usedNameIndices } = collectKeptSegments(sourceMap.mappings, indicesToKeep)

  // Build new sources array and create index mapping
  const newSources: string[] = []
  const newSourcesContent: (string | null)[] = []
  const sourceIndexMap = new Map<number, number>()

  for (const oldIndex of Array.from(indicesToKeep).sort((a, b) => a - b)) {
    const newIndex = newSources.length
    sourceIndexMap.set(oldIndex, newIndex)
    const source = sourceMap.sources[oldIndex]
    if (source !== undefined) {
      // Convert relative paths to absolute for better debugger support
      const absoluteSource = isAbsolute(source) ? source : resolve(dirname(sourceMapPath), source)
      newSources.push(absoluteSource)
    }
    if (sourceMap.sourcesContent) {
      newSourcesContent.push(sourceMap.sourcesContent[oldIndex] || null)
    }
  }

  // Build new names array and create index mapping
  const newNames: string[] = []
  const nameIndexMap = new Map<number, number>()

  if (sourceMap.names) {
    for (const oldIndex of Array.from(usedNameIndices).sort((a, b) => a - b)) {
      if (oldIndex < sourceMap.names.length) {
        const newIndex = newNames.length
        nameIndexMap.set(oldIndex, newIndex)
        const name = sourceMap.names[oldIndex]
        if (name !== undefined) {
          newNames.push(name)
        }
      }
    }
  }

  // Re-encode mappings with the compacted indices
  const newMappings = encodeKeptSegments(keptByLine, totalLines, sourceIndexMap, nameIndexMap)

  // Create optimized source map
  // Note: We don't include sourceRoot since we're using absolute paths
  const optimizedSourceMap: SourceMap = {
    version: sourceMap.version,
    file: sourceMap.file,
    sources: newSources,
    sourcesContent: newSourcesContent.length > 0 ? newSourcesContent : undefined,
    names: newNames.length > 0 ? newNames : undefined,
    mappings: newMappings,
  }

  // Create optimized content
  const optimizedContent = JSON.stringify(optimizedSourceMap)

  if (optimizedContent === sourceMapContent) {
    return
  }

  // 1. Write the optimized source map file
  await writeFile(sourceMapPath, optimizedContent, 'utf-8')

  // 2. Inline the source map into the .cjs file
  const cjsPath = sourceMapPath.replace('.cjs.map', '.cjs')
  let cjsContent = await readFile(cjsPath, 'utf-8')

  // Convert source map to base64
  const base64SourceMap = Buffer.from(optimizedContent, 'utf-8').toString('base64')
  const inlineSourceMap = `//# sourceMappingURL=data:application/json;base64,${base64SourceMap}`

  // Replace existing source map comment with inline version
  cjsContent = cjsContent.replace(/\/\/# sourceMappingURL=.*$/m, inlineSourceMap)

  // If no source map comment was found, append it
  if (!cjsContent.includes('//# sourceMappingURL=')) {
    cjsContent += `\n${inlineSourceMap}`
  }

  // Write the updated .cjs file
  await writeFile(cjsPath, cjsContent, 'utf-8')
}
