import path from 'path'
import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'

export async function generateComponentTypes(project: AgentProject): Promise<void> {
  const components = project.customComponents

  if (components.length === 0) {
    const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

declare module "@holocronlab/botruntime-runtime/_types/components" {
  export type CustomComponentMessage = never;
}
`
    const typesPath = path.join(project.path, '.adk', 'component-types.d.ts')
    await createFile(typesPath, await formatCode(content))
    return
  }

  const componentImports: string[] = []
  const payloadUnionMembers: string[] = []

  for (const comp of components) {
    const importPath = `../${comp.path.replace(/\.ts$/, '')}`
    componentImports.push(`import("${importPath}").${comp.export}`)
    payloadUnionMembers.push(
      `{ component: import("${importPath}").${comp.export}; props: Parameters<import("${importPath}").${comp.export}["encode"]>[0] }`
    )
  }

  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

declare module "@holocronlab/botruntime-runtime/_types/components" {
  export type CustomComponentMessage = ${payloadUnionMembers.join('\n    | ')};
}
`

  const typesPath = path.join(project.path, '.adk', 'component-types.d.ts')
  await createFile(typesPath, await formatCode(content))
}
