import { z } from '@holocronlab/botruntime-sdk'
import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'
import path from 'path'

export async function generateConfigurationTypes(project: AgentProject): Promise<void> {
  let configurationType = '{}'

  // Load the agent config to get configuration schema
  try {
    const configPath = path.join(project.path, 'agent.config.ts')
    // Bust module cache to ensure fresh config on type generation
    const configModule = await import(`${configPath}?t=${Date.now()}`)
    const config = configModule.default

    if (config?.configuration?.schema) {
      const configSchema = config.configuration.schema as z.ZodTypeAny
      if (configSchema.toTypescriptType) {
        configurationType = configSchema.toTypescriptType()
      }
    }
  } catch (error) {
    console.warn('Failed to load agent config for configuration types:', error)
  }

  // Generate the type definitions
  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

declare module "@holocronlab/botruntime-runtime/_types/configuration" {
  export type Configuration = ${configurationType};
}
`

  // Write to configuration-types.d.ts in the .adk folder
  const configTypesPath = path.join(project.path, '.adk', 'configuration-types.d.ts')
  await createFile(configTypesPath, await formatCode(content))
}
