import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'
import path from 'path'
import { z } from '@holocronlab/botruntime-sdk'

type EventDefinitionEntry = {
  schema?: z.ZodTypeAny
  description?: string
}

export async function generateEventTypes(project: AgentProject): Promise<void> {
  const defaultEvents = ['register: {}']
  // Collect all integration events
  const integrationEvents: string[] = []

  for (const int of project.integrations) {
    for (const event in int.definition?.events || []) {
      integrationEvents.push(`"${int.alias}:${event}": Integrations["${int.alias}"]["events"]["${event}"];`)
    }
  }

  // Collect custom events from agent.config.ts
  const customEvents: string[] = []

  // Access events from config - use type assertion since the config is dynamically loaded
  const config = project.config as Record<string, unknown> | undefined
  const customEventEntries = (config?.events || {}) as Record<string, EventDefinitionEntry>

  for (const [eventName, eventDef] of Object.entries(customEventEntries)) {
    const schema = eventDef.schema
    let payloadType = '{}'

    if (schema && typeof schema.toTypescriptType === 'function') {
      payloadType = schema.toTypescriptType()
    }

    customEvents.push(`"${eventName}": ${payloadType};`)
  }

  const allEvents = [...integrationEvents, ...customEvents, ...defaultEvents]

  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

type Integrations = import("@holocronlab/botruntime-runtime/_types/integrations").Integrations;

declare module "@holocronlab/botruntime-runtime/_types/events" {
  /**
   * Global Events type that includes all integration events and custom events.
   * Use this type to reference any event that can occur in the system.
   *
   * Events are namespaced by their source:
   * - Integration events: "<integration>:<eventName>" (e.g., "linear:issueCreated")
   * - Custom events: "<eventName>" (e.g., "orderPlaced", "userRegistered")
   */
  export type Events = {
${allEvents.map((e) => `    ${e}`).join('\n')}
  };

  // Export helper type for event names
  export type EventName = keyof Events;

  // Export helper to get event payload type
  export type EventPayload<T extends EventName> = Events[T];
}
`

  // Write to event-types.d.ts in the .adk folder
  const eventTypesPath = path.join(project.path, '.adk', 'event-types.d.ts')
  await createFile(eventTypesPath, await formatCode(content))
}
