import { z } from '@holocronlab/botruntime-sdk'
import crypto from 'crypto'
import path from 'path'

import { ParsedIntegration } from '../integrations/types.js'

const { transforms } = z
import { pascalCase, snakeCase } from '../utils/strings.js'
import { ADK_VERSION, relative, toMultilineComment, formatCode } from './utils.js'
import { getIntegrationAlias } from '../utils/ids.js'

const getIntegrationHash = (integration: ParsedIntegration): string => {
  return crypto
    .createHash('sha256')
    .update(
      `${integration.alias}|${integration.definition?.id}|${integration.definition?.version}|${integration.definition?.updatedAt}`
    )
    .digest('hex')
}

const getPascalAlias = (integration: ParsedIntegration) => pascalCase(getIntegrationAlias(integration.alias))

const getIntegrationNames = (integration: ParsedIntegration) => ({
  typings: {
    index: `Integration_All_${getPascalAlias(integration)}`,
    actions: `Integration_Actions_${getPascalAlias(integration)}`,
    channels: `Integration_Channels_${getPascalAlias(integration)}`,
    events: `Integration_Events_${getPascalAlias(integration)}`,
    users: `Integration_Users_${getPascalAlias(integration)}`,
    configurations: `Integration_Configurations_${getPascalAlias(integration)}`,
  },
  paths: {
    index: path.join(snakeCase(getPascalAlias(integration)), `index.ts`),
    actions: path.join(snakeCase(getPascalAlias(integration)), `actions.ts`),
    channels: path.join(snakeCase(getPascalAlias(integration)), `channels.ts`),
    events: path.join(snakeCase(getPascalAlias(integration)), `events.ts`),
    users: path.join(snakeCase(getPascalAlias(integration)), `users.ts`),
    configurations: path.join(snakeCase(getPascalAlias(integration)), `configurations.ts`),
  },
})

export async function generateIntegrationTypes(integration: ParsedIntegration): Promise<{
  names: ReturnType<typeof getIntegrationNames>
  files: Record<string, string>
}> {
  const names = getIntegrationNames(integration)
  const hash = getIntegrationHash(integration)

  const rel = (to: string): string => {
    const from = names.paths.index
    return relative(from, to).replace(/\.ts$/i, '')
  }

  let tIndex = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition?.name}
  // Version: ${integration.definition?.version}
  // File: ${names.paths.index}
  // Hash: ${hash}
  // Updated at: ${integration.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  import { Integration_Actions_${getPascalAlias(integration)} } from "${rel(names.paths.actions)}";
  import { Integration_Channels_${getPascalAlias(integration)} } from "${rel(names.paths.channels)}";
  import { Integration_Events_${getPascalAlias(integration)} } from "${rel(names.paths.events)}";
  import { Integration_Users_${getPascalAlias(integration)} } from "${rel(names.paths.users)}";
  import { Integration_Configurations_${getPascalAlias(integration)} } from "${rel(names.paths.configurations)}";

  export * from "${rel(names.paths.actions)}";
  export * from "${rel(names.paths.channels)}";
  export * from "${rel(names.paths.events)}";
  export * from "${rel(names.paths.users)}";
  export * from "${rel(names.paths.configurations)}";

  export type Integration_All_${getPascalAlias(integration)} = {
    actions: Integration_Actions_${getPascalAlias(integration)};
    channels: Integration_Channels_${getPascalAlias(integration)};
    events: Integration_Events_${getPascalAlias(integration)};
    users: Integration_Users_${getPascalAlias(integration)};
    configurations: Integration_Configurations_${getPascalAlias(integration)};
  };
  `

  let tActions = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition?.name}
  // Version: ${integration.definition?.version}
  // File: ${names.paths.actions}
  // Hash: ${hash}
  // Updated at: ${integration.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  export type Integration_Actions_${getPascalAlias(integration)} = {`

  for (const [name, action] of Object.entries(integration.definition!.actions)) {
    const input = transforms.fromJSONSchema(action.input.schema).toTypescriptType()
    const output = transforms.fromJSONSchema(action.output.schema).toTypescriptType()

    tActions += `
    ${toMultilineComment(`Title: ${action.title || name}\nDescription: ${action.description || 'No description'}`)}
    "${name}": {
      input: ${input};
      output: ${output};
    },\n`
  }

  tActions += `};`

  let tChannels = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition?.name}
  // Version: ${integration.definition?.version}
  // File: ${names.paths.channels}
  // Hash: ${hash}
  // Updated at: ${integration.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  export type Integration_Channels_${getPascalAlias(integration)} = {`

  for (const [channelName, channelDef] of Object.entries(integration.definition?.channels || {})) {
    const convoTagsRecord =
      '{' +
      Object.keys(channelDef.conversation?.tags || {}).reduce((acc, t) => {
        const tag = channelDef.conversation.tags[t]!
        const comment = toMultilineComment(`Title: ${tag?.title}\nDescription: ${tag.description}`)
        // Use alias instead of ref.fullName since the API returns tags with the alias prefix
        acc += `${comment}\n["${integration.alias}:${t}"]?: string,\n`
        return acc
      }, '') +
      '}'

    const msgTagsUnion =
      '{' +
      Object.keys(channelDef.message?.tags || {}).reduce((acc, t) => {
        const tag = channelDef.message.tags[t]!
        const comment = toMultilineComment(`Title: ${tag?.title}\nDescription: ${tag.description}`)
        // Use alias instead of ref.fullName since the API returns tags with the alias prefix
        acc += `${comment}\n["${integration.alias}:${t}"]?: string,\n`
        return acc
      }, '') +
      '}'

    let messagesBlock = ''
    for (const [messageName, messageDef] of Object.entries(channelDef.messages || {})) {
      const messageType = transforms.fromJSONSchema(messageDef.schema).toTypescriptType()
      messagesBlock += `\n"${messageName}": ${messageType};\n`
    }

    tChannels += `
    ${toMultilineComment(
      `Title: ${channelDef.title || channelName}\nDescription: ${channelDef.description || 'No description'}`
    )}
    "${channelName}": {
      conversation: {
        tags: ${convoTagsRecord};
      };
      message: {
        tags: ${msgTagsUnion};
      };
      messages: {${messagesBlock}
      };
    },`
  }

  tChannels += `
  };
  `

  let tEvents = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition!.name}
  // Version: ${integration.definition!.version}
  // File: ${names.paths.events}
  // Hash: ${hash}
  // Updated at: ${integration.definition!.updatedAt}
  ////////////////////////////////////////////////////////

  export type Integration_Events_${getPascalAlias(integration)} = {`

  for (const [eventName, event] of Object.entries(integration.definition!.events || {})) {
    const payloadType = transforms.fromJSONSchema(event.schema).toTypescriptType()
    const attributesComment = Object.keys(event.attributes || {}).length
      ? `\nAttributes:\n${Object.entries(event.attributes!)
          .map(([k, v]) => `  - ${k}: ${v}`)
          .join('\n')}`.trim()
      : ''

    tEvents += `
    ${toMultilineComment(
      `Title: ${event.title || eventName}\nDescription: ${event.description || 'No description'}${attributesComment}`
    )}
    "${eventName}": ${payloadType};
    `
  }

  tEvents += `
  };
  `

  let tUsers = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition?.name}
  // Version: ${integration.definition?.version}
  // File: ${names.paths.users}
  // Hash: ${hash}
  // Updated at: ${integration.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  export type Integration_Users_${getPascalAlias(integration)} = {`

  const userTagKeys = Object.keys(integration.definition?.user?.tags || {})
  const userTagsUnion = userTagKeys.length
    ? userTagKeys
        .map((t) => {
          const tag = (integration.definition?.user!.tags ?? ({} as Record<string, unknown>))[t] as
            | Record<string, unknown>
            | undefined
          const comment = toMultilineComment(`Title: ${tag?.title}\nDescription: ${tag?.description}`)
          // Use alias instead of ref.fullName since the API returns tags with the alias prefix
          return `${comment}\n"${integration.alias}:${t}"\n`
        })
        .join(' | ')
    : 'never'

  tUsers += `
    tags: ${userTagsUnion};
  };
  `

  // Generate configurations map type with JSDoc comments
  let tConfigurations = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Integration: ${integration.definition?.name}
  // Version: ${integration.definition?.version}
  // File: ${names.paths.configurations}
  // Hash: ${hash}
  // Updated at: ${integration.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  export type Integration_Configurations_${getPascalAlias(integration)} = `

  const configEntries: string[] = []

  // Add "default" configuration from .configuration if it exists
  if (integration.definition?.configuration) {
    const defaultConfig = integration.definition.configuration as Record<string, unknown>
    const title = defaultConfig.title || 'Default'
    const description = defaultConfig.description || 'Default configuration'
    const schema = defaultConfig.schema

    let tsType = '{}'
    if (schema) {
      tsType = transforms.fromJSONSchema(schema).toTypescriptType()
    }

    // Build JSDoc comment
    const jsdocLines: string[] = ['/**']
    jsdocLines.push(`   * @title ${title}`)
    if (description) {
      jsdocLines.push(`   * ${description}`)
    }
    jsdocLines.push('   */')

    configEntries.push(`${jsdocLines.join('\n  ')}\n  default: ${tsType}`)
  }

  // Add configurations from .configurations
  if (integration.definition?.configurations) {
    for (const [key, config] of Object.entries(integration.definition.configurations)) {
      const configRecord = config as Record<string, unknown>
      const title = configRecord.title || key
      const description = configRecord.description || ''
      const schema = configRecord.schema

      let tsType = '{}'
      if (schema) {
        tsType = transforms.fromJSONSchema(schema).toTypescriptType()
      }

      // Build JSDoc comment
      const jsdocLines: string[] = ['/**']
      jsdocLines.push(`   * @title ${title}`)
      if (description) {
        jsdocLines.push(`   * ${description}`)
      }
      jsdocLines.push('   */')

      configEntries.push(`${jsdocLines.join('\n  ')}\n  ${key}: ${tsType}`)
    }
  }

  if (configEntries.length > 0) {
    tConfigurations += `{
  ${configEntries.join(';\n  ')};
};`
  } else {
    tConfigurations += `Record<string, never>;`
  }

  return {
    names,
    files: {
      [names.paths.index]: await formatCode(tIndex),
      [names.paths.actions]: await formatCode(tActions),
      [names.paths.channels]: await formatCode(tChannels),
      [names.paths.events]: await formatCode(tEvents),
      [names.paths.users]: await formatCode(tUsers),
      [names.paths.configurations]: await formatCode(tConfigurations),
    },
  }
}
