import { z } from '@holocronlab/botruntime-sdk'
import crypto from 'crypto'
import path from 'path'

import { ParsedPlugin } from '../plugins/types.js'

const { transforms } = z
import { pascalCase, snakeCase } from '../utils/strings.js'
import { ADK_VERSION, relative, toMultilineComment, formatCode } from './utils.js'
import { getPluginAlias } from '../utils/ids.js'

/**
 * Recursively strip $ref entries from a JSON Schema, replacing them with
 * a permissive object type. Plugin schemas may contain interface entity
 * refs (e.g. "interface:hitl/entities/hitlSession") that can't be resolved
 * without fetching the full interface definition. Rather than losing all
 * type info, we replace just the ref'd properties with Record<string, unknown>.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON Schema objects are inherently loosely typed
function stripRefs(schema: Record<string, any>): Record<string, any> {
  if (typeof schema !== 'object' || schema === null) {
    return schema
  }

  if (schema.$ref) {
    return { type: 'object', additionalProperties: true, 'x-stripped-ref': schema.$ref }
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON Schema objects are inherently loosely typed
  const result: Record<string, any> = {}
  for (const [key, value] of Object.entries(schema)) {
    if (key === '$defs' || key === 'definitions') {
      // Drop local defs since we're stripping all refs
      continue
    }
    if (Array.isArray(value)) {
      result[key] = value.map((item) => (typeof item === 'object' && item !== null ? stripRefs(item) : item))
    } else if (typeof value === 'object' && value !== null) {
      result[key] = stripRefs(value)
    } else {
      result[key] = value
    }
  }
  return result
}

/**
 * Convert a JSON Schema to a TypeScript type string.
 * Strips $ref entries that can't be locally resolved before conversion.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON Schema objects are inherently loosely typed
function jsonSchemaToTypescript(schema: Record<string, any>): string {
  const cleaned = stripRefs(schema)
  return transforms.fromJSONSchema(cleaned).toTypescriptType()
}

const getPluginHash = (plugin: ParsedPlugin): string => {
  return crypto
    .createHash('sha256')
    .update(`${plugin.alias}|${plugin.definition?.id}|${plugin.definition?.version}|${plugin.definition?.updatedAt}`)
    .digest('hex')
}

const getPascalAlias = (plugin: ParsedPlugin) => pascalCase(getPluginAlias(plugin.alias))

const getPluginNames = (plugin: ParsedPlugin) => ({
  typings: {
    index: `Plugin_All_${getPascalAlias(plugin)}`,
    actions: `Plugin_Actions_${getPascalAlias(plugin)}`,
  },
  paths: {
    index: path.join(snakeCase(getPascalAlias(plugin)), `index.ts`),
    actions: path.join(snakeCase(getPascalAlias(plugin)), `actions.ts`),
  },
})

export async function generatePluginTypes(plugin: ParsedPlugin): Promise<{
  names: ReturnType<typeof getPluginNames>
  files: Record<string, string>
}> {
  const names = getPluginNames(plugin)
  const hash = getPluginHash(plugin)

  const rel = (to: string): string => {
    const from = names.paths.index
    return relative(from, to).replace(/\.ts$/i, '')
  }

  let tIndex = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Plugin: ${plugin.definition?.name}
  // Version: ${plugin.definition?.version}
  // File: ${names.paths.index}
  // Hash: ${hash}
  // Updated at: ${plugin.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  import { Plugin_Actions_${getPascalAlias(plugin)} } from "${rel(names.paths.actions)}";

  export * from "${rel(names.paths.actions)}";

  export type Plugin_All_${getPascalAlias(plugin)} = {
    actions: Plugin_Actions_${getPascalAlias(plugin)};
  };
  `

  let tActions = `
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: ${ADK_VERSION}
  // Plugin: ${plugin.definition?.name}
  // Version: ${plugin.definition?.version}
  // File: ${names.paths.actions}
  // Hash: ${hash}
  // Updated at: ${plugin.definition?.updatedAt}
  ////////////////////////////////////////////////////////

  export type Plugin_Actions_${getPascalAlias(plugin)} = {`

  for (const [name, action] of Object.entries(plugin.definition!.actions)) {
    const input = jsonSchemaToTypescript(action.input.schema)
    const output = jsonSchemaToTypescript(action.output.schema)

    tActions += `
    ${toMultilineComment(`Title: ${action.title || name}\nDescription: ${action.description || 'No description'}`)}
    "${name}": {
      input: ${input};
      output: ${output};
    },\n`
  }

  tActions += `};`

  return {
    names,
    files: {
      [names.paths.index]: await formatCode(tIndex),
      [names.paths.actions]: await formatCode(tActions),
    },
  }
}
