import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'
import path from 'path'

export async function generatePluginActionTypes(project: AgentProject): Promise<void> {
  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

type Plugins = import("@holocronlab/botruntime-runtime/_types/plugins").Plugins;

declare module "@holocronlab/botruntime-runtime/_types/plugin-actions" {

export interface CallableAction<I, O> {
  (input: I): Promise<O>;
}

type Callable<T> = T extends { input: infer I; output: infer O }
  ? CallableAction<I, O>
  : never;

type PluginsMap<T> = {
  [Plugin in keyof T]: T[Plugin] extends { actions: infer Actions }
    ? {
        actions: {
          [Action in keyof Actions]: Callable<Actions[Action]>;
        };
      }
    : never;
};

export type PluginActions = PluginsMap<Plugins>;
}
`

  const pluginActionTypesPath = path.join(project.path, '.adk', 'plugin-action-types.d.ts')
  await createFile(pluginActionTypesPath, await formatCode(content))
}
