import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'
import path from 'path'

export async function generateSecretTypes(project: AgentProject): Promise<void> {
  let secretsType = '{}'

  // Load the agent config to get secrets definitions
  try {
    const configPath = path.join(project.path, 'agent.config.ts')
    // Bust module cache to ensure fresh config on type generation
    const configModule = await import(`${configPath}?t=${Date.now()}`)
    const config = configModule.default

    if (config?.secrets) {
      const secrets = config.secrets as Record<string, { optional?: boolean; description?: string }>
      const entries = Object.entries(secrets)

      if (entries.length > 0) {
        const props = entries.map(([key, def]) => {
          const type = def.optional ? 'string | undefined' : 'string'
          return `  ${JSON.stringify(key)}: ${type}`
        })
        secretsType = `{\n${props.join('\n')}\n}`
      }
    }
  } catch (error) {
    console.warn('Failed to load agent config for secret types:', error)
  }

  // Generate the type definitions
  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

declare module "@holocronlab/botruntime-runtime/_types/secrets" {
  export type Secrets = ${secretsType};
}
`

  // Write to secret-types.d.ts in the .adk folder
  const secretTypesPath = path.join(project.path, '.adk', 'secret-types.d.ts')
  await createFile(secretTypesPath, await formatCode(content))
}
