import { AgentProject } from '../agent-project/agent-project.js'
import { ADK_VERSION, formatCode } from './utils.js'
import { createFile } from '../utils/fs.js'
import path from 'path'
import { BUILT_IN_TAGS } from '@holocronlab/botruntime-runtime/definition'

/**
 * Helper to generate tag type strings from tag definitions
 */
function generateTagTypeString(
  builtInTags: Record<string, { title: string; description: string }>,
  configTags?: Record<string, { title: string; description: string }>
): string {
  const builtInTagStrings = Object.entries(builtInTags).map(([key, tag]) => {
    const jsdoc = tag.description
      ? `/**\n   * ${tag.title}\n   * \n   * ${tag.description}\n   */\n  `
      : `/** ${tag.title} */\n  `
    return `${jsdoc}${key}?: string | undefined`
  })

  const configTagStrings = configTags
    ? Object.entries(configTags).map(([key, tag]) => {
        const jsdoc = tag.description
          ? `/**\n   * ${tag.title}\n   * \n   * ${tag.description}\n   */\n  `
          : `/** ${tag.title} */\n  `
        return `${jsdoc}${key}?: string | undefined`
      })
    : []

  const allTags = [...builtInTagStrings, ...configTagStrings]

  if (allTags.length === 0) {
    return 'Record<string, string | undefined>'
  }

  return `{\n  ${allTags.join('\n  ')}\n}`
}

export async function generateTagTypes(project: AgentProject): Promise<void> {
  let botTagsType = 'Record<string, string | undefined>'
  let userTagsType = 'Record<string, string | undefined>'
  let conversationTagsType = 'Record<string, string | undefined>'
  let messageTagsType = 'Record<string, string | undefined>'
  let workflowTagsType = 'Record<string, string | undefined>'

  // Load the agent config to get tag definitions
  try {
    const configPath = path.join(project.path, 'agent.config.ts')
    // Bust module cache to ensure fresh config on type generation
    const configModule = await import(`${configPath}?t=${Date.now()}`)
    const config = configModule.default

    // Generate all tag types with built-in tags
    botTagsType = generateTagTypeString(BUILT_IN_TAGS.bot, config?.bot?.tags)
    userTagsType = generateTagTypeString(BUILT_IN_TAGS.user, config?.user?.tags)
    conversationTagsType = generateTagTypeString(BUILT_IN_TAGS.conversation, config?.conversation?.tags)
    messageTagsType = generateTagTypeString(BUILT_IN_TAGS.message, config?.message?.tags)
    workflowTagsType = generateTagTypeString(BUILT_IN_TAGS.workflow, config?.workflow?.tags)
  } catch (error) {
    console.warn('Failed to load agent config for tag types:', error)
  }

  // Generate the type definitions
  const content = `
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: ${ADK_VERSION}
// Generated at: ${new Date().toISOString()}
////////////////////////////////////////////////////////

declare module "@holocronlab/botruntime-runtime/_types/tags" {
  /**
   * Bot-level tags defined in agent.config.ts
   */
  export type BotTags = ${botTagsType};

  /**
   * User-level tags defined in agent.config.ts
   */
  export type UserTags = ${userTagsType};

  /**
   * Conversation-level tags defined in agent.config.ts
   */
  export type ConversationTags = ${conversationTagsType};

  /**
   * Message-level tags defined in agent.config.ts
   */
  export type MessageTags = ${messageTagsType};

  /**
   * Workflow-level tags defined in agent.config.ts
   */
  export type WorkflowTags = ${workflowTagsType};
}
`

  // Write to tag-types.d.ts in the .adk folder
  const tagTypesPath = path.join(project.path, '.adk', 'tag-types.d.ts')
  await createFile(tagTypesPath, await formatCode(content))
}
