import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { createRequire } from 'module'
import { AdkError } from '@holocronlab/botruntime-analytics'
import { ADK_VERSION, formatCode } from '../generators/utils.js'
// @ts-expect-error - Bun import attribute for text
import aiAssistantInstructions from './ai-assistant-instructions.template.md' with { type: 'text' }

// File extensions treated as text (placeholder substitution + formatting applied).
// Everything else is copied as binary with no transformation.
const TEXT_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.json',
  '.md',
  '.txt',
  '.yml',
  '.yaml',
  '.html',
  '.css',
  '.svg',
  '.gitignore',
])

function isTextFile(filename: string): boolean {
  // .gitignore has no extension but is text
  if (filename === '.gitignore') return true
  const ext = path.extname(filename).toLowerCase()
  return TEXT_EXTENSIONS.has(ext)
}

const DEFAULT_GITIGNORE = `# Dependencies
node_modules/
.pnpm-store/

# Build outputs
dist/
.adk/

# Environment files
.env
.env.local
.env.production

# Local development
agent.local.json

# MCP configuration (generated by agent tooling)
.mcp.json

# IDE files
.vscode/
.idea/
*.swp
*.swo

# OS files
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Runtime files
*.pid
*.seed
*.pid.lock
`

export interface TemplateConfig {
  name: string
  title?: string
  description: string
  category: string
  complexity: 'beginner' | 'intermediate' | 'advanced'
  inspired_by?: string
  dependencies: { integrations: string[]; plugins: string[] }
}

export interface TemplateRegistry {
  templates: TemplateConfig[]
}

export class AgentProjectGenerator {
  private projectPath: string
  private projectName: string
  private packageManager: string
  private template: string

  constructor(projectPath: string, packageManager: string = 'bun', template: string = 'blank') {
    this.projectPath = path.resolve(projectPath)
    this.projectName = path.basename(this.projectPath)
    this.packageManager = packageManager
    this.template = template
  }

  async generate(): Promise<void> {
    this.ensureEmptyDirectory()

    const templateDir = this.resolveTemplateDir()
    await this.copyTemplateFiles(templateDir)

    // Only create these if the template didn't provide them.
    const templateConfig = this.getTemplateConfig()
    if (!fs.existsSync(path.join(this.projectPath, 'package.json'))) {
      this.createPackageJson(templateConfig)
    }
    if (!fs.existsSync(path.join(this.projectPath, 'tsconfig.json'))) {
      this.createTsConfig()
    }
    if (!fs.existsSync(path.join(this.projectPath, '.gitignore'))) {
      this.createGitignore()
    }
    if (!fs.existsSync(path.join(this.projectPath, 'CLAUDE.md'))) {
      this.createAIAssistantInstructions()
    }
  }

  /**
   * Returns the list of available templates from the registry.
   */
  static getAvailableTemplates(): TemplateConfig[] {
    try {
      const templatesRoot = AgentProjectGenerator.getTemplatesRoot()
      const configPath = path.join(templatesRoot, 'template.config.json')

      if (!fs.existsSync(configPath)) {
        return []
      }

      const raw = fs.readFileSync(configPath, 'utf-8')
      const registry: TemplateRegistry = JSON.parse(raw)
      return registry.templates
    } catch {
      // getTemplatesRoot throws if no candidates found — that's expected
      // when templates haven't been extracted yet (compiled binary first run)
      return []
    }
  }

  /**
   * Returns the dependencies (integrations and plugins) for the current template.
   */
  getDependencies(): { integrations: string[]; plugins: string[] } {
    return this.getTemplateConfig()?.dependencies ?? { integrations: [], plugins: [] }
  }

  private getTemplateConfig(): TemplateConfig | undefined {
    const templates = AgentProjectGenerator.getAvailableTemplates()
    return templates.find((t) => t.name === this.template)
  }

  /**
   * Optional external templates provider. When set (e.g., by the CLI from embedded assets),
   * this is used as the templates root instead of filesystem resolution.
   */
  private static _templatesRootOverride: string | null = null

  static setTemplatesRoot(dir: string): void {
    AgentProjectGenerator._templatesRootOverride = dir
  }

  static resetTemplatesRoot(): void {
    AgentProjectGenerator._templatesRootOverride = null
  }

  private static getTemplatesRoot(): string {
    // If an override was set (e.g., CLI extracted templates from embedded assets), use it
    if (AgentProjectGenerator._templatesRootOverride) {
      return AgentProjectGenerator._templatesRootOverride
    }

    // Strategy: find the @holocronlab/botruntime-adk package root, then look for templates/
    // This works regardless of where the code is bundled (CLI dist, ADK dist, etc.)
    const candidates: string[] = []

    // 1. Resolve from @holocronlab/botruntime-adk package.json location (ESM-compatible)
    try {
      const esmRequire = createRequire(import.meta.url)
      const adkPkgPath = esmRequire.resolve('@holocronlab/botruntime-adk/package.json')
      const adkRoot = path.dirname(adkPkgPath)
      candidates.push(path.join(adkRoot, 'dist', 'templates'))
      candidates.push(path.join(adkRoot, 'templates'))
    } catch {
      // Not resolvable via require.resolve (e.g., running from source or compiled binary)
    }

    // 2. Relative to this file (works when running ADK directly)
    const thisDir = path.dirname(fileURLToPath(import.meta.url))
    candidates.push(path.resolve(thisDir, 'templates'))
    candidates.push(path.resolve(thisDir, '../../templates'))

    // 3. Relative to process.execPath (compiled binary with templates alongside)
    candidates.push(path.join(path.dirname(process.execPath), 'templates'))

    for (const candidate of candidates) {
      if (fs.existsSync(candidate) && fs.existsSync(path.join(candidate, 'template.config.json'))) {
        return candidate
      }
    }

    const tried = candidates.map((c) => `  - ${c}`).join('\n')
    throw new AdkError({
      code: 'TEMPLATES_DIR_NOT_FOUND',
      expected: false,
      message: `Could not find templates directory.\n\nSearched:\n${tried}\n\nReinstall @holocronlab/botruntime-adk; its distribution must include dist/templates.`,
    })
  }

  private resolveTemplateDir(): string {
    const templatesRoot = AgentProjectGenerator.getTemplatesRoot()
    const templateDir = path.join(templatesRoot, this.template)

    if (!fs.existsSync(templateDir)) {
      const available = AgentProjectGenerator.getAvailableTemplates()
      const names = available.map((t) => `  - ${t.name}: ${t.description}`).join('\n')
      const validNames = available.map((t) => t.name).join(', ')
      throw new AdkError({
        code: 'UNKNOWN_TEMPLATE',
        expected: true,
        message: `Unknown template: "${this.template}"\n\nAvailable templates:\n${names || '  (none found)'}`,
        suggestion: validNames
          ? `Re-run with a valid template name (one of: ${validNames}).`
          : 'Re-run with a valid template name.',
      })
    }

    // Verify template has at least an agent.config.ts
    const configFile = path.join(templateDir, 'agent.config.ts')
    if (!fs.existsSync(configFile)) {
      throw new AdkError({
        code: 'TEMPLATE_INVALID',
        expected: false,
        message: `Template "${this.template}" is missing agent.config.ts`,
      })
    }

    return templateDir
  }

  private async copyTemplateFiles(templateDir: string): Promise<void> {
    const substitutions: Record<string, string> = {
      '{{projectName}}': this.projectName,
      '{{runtimeVersion}}': ADK_VERSION,
      '{{packageManager}}': this.packageManager,
    }

    await this.copyDirRecursive(templateDir, this.projectPath, substitutions)
  }

  private async copyDirRecursive(src: string, dest: string, substitutions: Record<string, string>): Promise<void> {
    if (!fs.existsSync(dest)) {
      fs.mkdirSync(dest, { recursive: true })
    }

    const entries = fs.readdirSync(src, { withFileTypes: true })

    for (const entry of entries) {
      const srcPath = path.join(src, entry.name)
      const destPath = path.join(dest, entry.name)

      if (entry.isDirectory()) {
        await this.copyDirRecursive(srcPath, destPath, substitutions)
      } else if (isTextFile(entry.name)) {
        // Text files: read as utf-8, apply substitutions, optionally format
        let content = fs.readFileSync(srcPath, 'utf-8')

        for (const [placeholder, value] of Object.entries(substitutions)) {
          content = content.replaceAll(placeholder, value)
        }

        // Warn if any unresolved placeholders remain
        const remaining = content.match(/\{\{[a-zA-Z]+\}\}/g)
        if (remaining) {
          console.warn(`Warning: unresolved placeholders in ${entry.name}: ${remaining.join(', ')}`)
        }

        // Format TypeScript files (non-fatal: fall back to unformatted on error)
        if (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx')) {
          try {
            content = await formatCode(content, destPath)
          } catch {
            // Formatter unavailable or syntax issue — write unformatted
          }
        }

        fs.writeFileSync(destPath, content)
      } else {
        // Binary files: copy as-is with no transformation
        fs.copyFileSync(srcPath, destPath)
      }
    }
  }

  private ensureEmptyDirectory(): void {
    if (!fs.existsSync(this.projectPath)) {
      fs.mkdirSync(this.projectPath, { recursive: true })
    }

    const files = fs.readdirSync(this.projectPath)
    if (files.length > 0) {
      throw new AdkError({
        code: 'TARGET_DIR_NOT_EMPTY',
        expected: true,
        message: `Directory ${this.projectPath} is not empty. Please use an empty directory.`,
        suggestion: 'Use an empty directory or pass the overwrite option to replace the existing contents.',
      })
    }
  }

  private createPackageJson(templateConfig?: TemplateConfig): void {
    this.writeJsonFile('package.json', {
      name: this.projectName,
      version: '1.0.0',
      description: templateConfig?.description ?? 'A Holocron agent built with botruntime ADK',
      type: 'module',
      scripts: {
        dev: 'brt dev',
        'dev:check': 'brt dev --check',
        typecheck: 'tsc --noEmit',
        deploy: 'brt deploy --adk',
      },
      dependencies: {
        '@holocronlab/botruntime-runtime': `^${ADK_VERSION}`,
      },
      devDependencies: {
        '@holocronlab/brt': '^0.6.0',
        typescript: '^5.9.3',
      },
    })
  }

  private createTsConfig(): void {
    this.writeJsonFile('tsconfig.json', {
      compilerOptions: {
        target: 'ES2022',
        module: 'ES2022',
        moduleResolution: 'Bundler',
        lib: ['ES2022', 'DOM'],
        outDir: './dist',
        rootDir: '.',
        strict: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        moduleDetection: 'force',
        resolveJsonModule: true,
        jsx: 'react',
        allowImportingTsExtensions: true,
        noEmit: true,
        paths: {
          '@holocronlab/botruntime-runtime/_types/*': ['./.adk/*-types'],
        },
      },
      include: ['src/**/*', '*.ts', '.adk/*.d.ts'],
      exclude: ['node_modules', 'dist'],
    })
  }

  private createGitignore(): void {
    this.writeFile('.gitignore', DEFAULT_GITIGNORE)
  }

  private createAIAssistantInstructions(): void {
    const content = aiAssistantInstructions as string
    this.writeFile('CLAUDE.md', content)
    this.writeFile('AGENTS.md', content)
  }

  private writeFile(relativePath: string, content: string): void {
    const filePath = path.join(this.projectPath, relativePath)
    fs.writeFileSync(filePath, content)
  }

  private writeJsonFile(relativePath: string, data: unknown): void {
    this.writeFile(relativePath, JSON.stringify(data, null, 2) + '\n')
  }
}
